[build]
  command = "npm run build"
  publish = ".next"

# Redirect non-www to www (primary domain)
[[redirects]]
  from = "https://wordgamedb.com/*"
  to = "https://www.wordgamedb.com/:splat"
  status = 301

[build.environment]
  NODE_VERSION = "18"
